### PR TITLE
refactor: handle states with useReducer

### PR DESCRIPTION
**Pull request by sepehrity**
Hi, I rewrote `useTimer` with `useReducer` and TypeScript to handle the states.

### CODE REVIEW

**Comment by thibaultboursier** [comment]
Hello @sepehrity, thanks for this work. I'm going to check it soon.

**Comment by sepehrity** [comment]
I’m happy to help, @thibaultboursier. That's Great.

**Review by thibaultboursier — APPROVED** [review]

**Comment by thibaultboursier** [comment]
Thanks for your work @sepehrity. I'll make some very minor changes before merging it on master branch.

**Comment by thibaultboursier** [comment]
@sepehrity I'm going to release **1.4.0** version. I included your work inside. https://github.com/thibaultboursier/use-timer/pull/36/files. Thanks again!

**Comment by sepehrity** [comment]
@thibaultboursier I'm glad to hear that it helped.

**Pull request merged**
